name: Run unit tests
on: [push, pull_request, workflow_dispatch]

jobs:
  vitest:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [16, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          yarn install
      - name: Test
        run: |
          yarn run test run --reporter verbose
